### ISSUE TITLE
How to install corretly?

### ISSUE THREAD

**Issue by huglester** [umpirsky/centipede#16]
Hello,

what would be the 'correct way' to install it?
Somehow simple composer requireumpirsky/centipede:dev-master did not work..

I needed to specify pull paths.. composer.json example:
```json
{
    "require": {
        "react/promise": "dev-master",
        "umpirsky/centipede": "dev-master",
        "umpirsky/centipede-crawler": "dev-master"
    },

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/umpirsky/centipede"
        },
        {
            "type": "vcs",
            "url": "https://github.com/umpirsky/centipede-crawler"
        }
    ]
}
```

**Comment by umpirsky** [comment]
Hello @huglester, it is still in development, so minimum stability must be dev:

```json
{
    "require": {
        "umpirsky/centipede": "dev-master"
    },
    "minimum-stability": "dev"
}
```

**Comment by huglester** [comment]
Thanks, did not think about that...

one more small question (don't wanna flood issues):
```php
./vendor/bin/centipede run http://www.altevents.darbai.webas.lt/
200 http://www.altevents.darbai.webas.lt/
```
Why so? there are more links? but it only checks the mainpage?

**Comment by umpirsky** [comment]
@huglester Will check when I have some time, please open new issue. ;)

I guess it's in [UrlExtractor](https://github.com/umpirsky/centipede-crawler/blob/master/src/Centipede/Extractor/UrlExtractor.php), you can debug if you wish.

Thanks for reporting.
