### ISSUE TITLE
Better support for depth argument

### ISSUE THREAD

**Issue by Pierstoval** [umpirsky/centipede#22]
Actually, when you have a link to the root url on any website, if you use the `depth` argument to crawl a website, this "brand link" will be crawled each time.

I'd recommend to add some kind of system that will enhance readability for the explored urls.
1. First, add something to the crawler that will store all crawled urls. A simple array with `url => true` pair and some `isset`s would permit this kind of use.
2. Add some kind of "level" informations in the logs.

For example, here is the output of this command:

``` bash
$ centipede run https://github.com 3
200 https://github.com
200 https://github.com/join
200 https://github.com/join
200 https://github.com/join
200 https://github.com/login?return_to=%2Fjoin
200 https://github.com/explore
200 https://github.com/features
200 https://github.com/blog
200 https://github.com/about
200 https://github.com/site/terms
200 https://github.com/site/privacy
200 https://github.com/security
200 https://github.com/contact
200 https://github.com/login
200 https://github.com/login?return_to=%2Flogin
200 https://github.com/login?return_to=%2Flogin
200 https://github.com/password_reset
200 https://github.com/plans
200 https://github.com/login?return_to=%2Fpricing
200 https://github.com/login?return_to=%2Fpricing
200 https://github.com/signup
200 https://github.com/early_access/large_file_storage?utm_source=github_site&utm_medium=pricing_signup_link&utm_campaign=gitlfs
200 https://github.com/login?return_to=%2Fearly_access%2Fgit-lfs
200 https://github.com/join?return_to=%2Fearly_access%2Fgit-lfs
200 mailto:support@github.com
200 https://github.com/plans
200 https://github.com/integrations
```

Here, I don't know where all different were "clicked from". Maybe I could guess, maybe not. The `/join` is seen many times, which is not much correct...

Edit (for this part): In fact, a structure I'd like to see might be something like this:

``` bash
$ centipede run http://example.com/
200 http://example.com/about
200 > http://example.com/about/team
200 > http://example.com/about/commercial
200 http://example.com/products
200 > http://example.com/products/specials
200 > > http://example.com/products/exclusive
```

Etc.

**Comment by umpirsky** [comment]
@Pierstoval Thanks for reporting. I noticed root url is repeated, will look into it.

Regarding HTTP errors, would be nice to report separated issue to track that one. Can you give some example please, not sure I understand your case?

**Comment by Pierstoval** [comment]
I changed the comments for the basic `depth` commentaries, I'll make another issue for the HTTP errors :)

**Comment by umpirsky** [comment]
@Pierstoval Great, thanks!
